### ISSUE TITLE
License for code re-use and modification? 

### ISSUE THREAD

**Issue by davisidarta** [KevinMoonLab/GRAE#10]
Thank you for your work and for this beautifully constructed software!

I'm looking forward to adapting some of the source code for another project. Naturally, I would like to pay my respects to the team who developed the code, and intended to do so by attaching the project license alongside a reference to this repository and to your publication at the top of the script. However, the project does not specify any license.  

How should someone interested in adapting the code available in this repository proceed?

Cheers,
Davi

**Comment by sachaMorin** [comment]
So sorry for the late reply. I need to check my email settings. I'll make sure to update the repo with a proper license later this week. I'll probably use GPL-3.0.

**Comment by sachaMorin** [comment]
After discussion with the team, we added the GPL3 license. Thanks again for your interest in the project!
