### ISSUE TITLE
Hello, I want to ask a question about the paper: what is the meaning of the numbers in brackets in Table 1? 

### ISSUE THREAD

**Issue by zheng547** [KevinMoonLab/GRAE#11]
![image](https://github.com/KevinMoonLab/GRAE/assets/54466644/44d6ef22-6fce-49cd-a1b2-1d7904cf17ee)

**Comment by sachaMorin** [comment]
Sorry for the late reply. That number would be the ranking!

**Comment by sachaMorin** [comment]
Closing. Feel free to reopen if you still have questions.
