### ISSUE TITLE
comet-ml==3.1.14 is not installed

### ISSUE THREAD

**Issue by JayaniLakshika** [KevinMoonLab/GRAE#9]
I tried to install the git repository via clone, and I got an error while running it. Then I tried to find the error and I found that the error occurred due to the installation of comet.ml ==3.1.14. Error note indicated that it's an error of the repo. 

Does anyone have the same issue as me? How should I fix it? Can you please guide me on this?

**Comment by sachaMorin** [comment]
Sorry for not seeing this before. This should be fixed as of https://github.com/KevinMoonLab/GRAE/commit/0a0c408ab936dc8ebcaaee49ce65c63ab6a27467. Thanks!
